import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Link from "next/link";
import { FileText } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | AIPromptNest",
  description: "Review the Terms of Service governing your use of the AIPromptNest website and prompt database.",
  alternates: {
    canonical: "/terms-of-service",
  },
};

export default function TermsOfServicePage() {
  const lastUpdated = "June 16, 2026";

  return (
    <main className="min-h-screen mesh-gradient text-foreground">
      <Navbar />

      <div className="max-w-4xl mx-auto px-4 md:px-8 pt-32 md:pt-40 mb-10">
        {/* Breadcrumbs */}
        <div className="flex items-center gap-2 text-[10px] font-black text-foreground/20 uppercase tracking-[0.2em] mb-8">
          <Link href="/" className="hover:text-primary transition-colors">Home</Link>
          <span className="opacity-50">/</span>
          <span className="text-foreground/40">Terms of Service</span>
        </div>

        {/* Header */}
        <div className="mb-12 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/10 border border-primary/20 text-primary text-[10px] font-bold uppercase tracking-widest">
            <FileText className="w-3 h-3" />
            Legal Center
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-white">
            Terms of Service
          </h1>
          <p className="text-xs text-white/40">
            Last Updated: {lastUpdated}
          </p>
        </div>

        {/* Content Box */}
        <div className="glass-dark border border-white/[0.08] p-8 md:p-12 rounded-[2.5rem] relative overflow-hidden space-y-8 text-foreground/75 leading-relaxed text-sm md:text-base">
          <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-[80px] pointer-events-none" />

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing, browsing, or using the services provided by AIPromptNest ("we", "our", "us") at <Link href="/" className="text-primary hover:underline font-semibold">aipromptnest.com</Link>, you acknowledge that you have read, understood, and agreed to be bound by these Terms of Service. If you do not agree with any part of these terms, please stop using our website.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              2. Description of Service
            </h2>
            <p>
              AIPromptNest provides users with a free directory of curated, tested, and categorized generative AI text prompt templates primarily optimized for Google Gemini. We reserve the right to modify, adjust, suspend, or discontinue any feature, category, or service at any time without notice.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              3. Intellectual Property & License
            </h2>
            <p>
              We want to make AI prompt engineering open and collaborative:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong className="text-white">Prompts:</strong> The text prompt combinations in our database are provided for copy-paste use without royalty or restriction. You can customize, publish, and use them for commercial or personal purposes.
              </li>
              <li>
                <strong className="text-white">Generated Images:</strong> The copyright and commercial terms of any images generated by submitting these prompts to Gemini models are governed strictly by Google Gemini's Terms of Service.
              </li>
              <li>
                <strong className="text-white">Website Assets:</strong> The website codebase, logos, page templates, CSS stylesheets, styling animations, and layout layouts are intellectual properties of AIPromptNest and may not be cloned, sold, or distributed without written permission.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              4. User Conduct
            </h2>
            <p>
              When navigating or interacting with AIPromptNest, you agree NOT to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Deploy bots, scrapers, web spiders, or automated scripts that crash, slow down, or systematically mirror our server pages.</li>
              <li>Transmit malware, Trojan horses, spyware, or spam content through our support forms.</li>
              <li>Submit plagiarized, offensive, illegal, or trademark-infringing prompts.</li>
              <li>Impersonate administrators, staff members, or other users.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              5. Disclaimer of Warranties
            </h2>
            <p className="italic">
              AIPromptNest is provided on an "as is" and "as available" basis without any warranties of any kind, whether express or implied. We do not guarantee that the prompts will run error-free, generate identical outcomes every time, or fulfill specific commercial project outcomes. AI image generation results can fluctuate dynamically.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              6. Limitation of Liability
            </h2>
            <p>
              In no event shall AIPromptNest, its team members, or partners be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your usage of or inability to use the prompt library, site servers, or generated digital items.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              7. Governing Law
            </h2>
            <p>
              These terms are governed by and construed in accordance with standard international web regulations and state laws. Any legal claims must be filed in the competent courts within the governing jurisdiction.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full" />
              8. Support & Feedback
            </h2>
            <p>
              For any clarification regarding these terms, permissions, or license inquiries, please navigate to our <Link href="/contact" className="text-primary hover:underline font-semibold">Contact Us</Link> page or send an inquiry to <a href="mailto:hello.aipromptnest@gmail.com" className="text-primary hover:underline font-semibold">hello.aipromptnest@gmail.com</a>.
            </p>
          </section>
        </div>
      </div>

      <Footer />
    </main>
  );
}
